;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 3.3, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.600000|            2|
;+----------------------------------------+

M48

METRIC,LZ,000.000
T01C0.600000
%
M71
G90
T01
X0237Y-0041
Y0039

M30
